### PR TITLE
Escape $_GET params to soothe psalm static analysis

### LINKED ISSUE #60: LDEW fails Psalm analysis
LDEW fails the Psalm taint analysis in the redcap security scanner. It says this:

```
# ./bin/scan modules/linear_data_entry_workflow_v0.0.0
Running composer install in /var/www/html/redcap_v13.6.0/ExternalModules/

------------------------------------------------------------
Running Psalm's Taint Analysis

ERROR: TaintedTextWithQuotes - ExternalModule.php:329:18 - Detected tainted text with possible quotes (see https://psalm.dev/274)
This is generally resolved by finding the simplest highlighted variable in the trace below (ideally a short string)
and wrapping it in htmlspecialchars($taintedString, ENT_QUOTES). In REDCap version 13.1.2, a $module->escape() method
was added that avoids boilerplate in more complex cases by recursively escaping arrays and preserving primitive types.
It will become the recommendation once most institutions update to that REDCap version.
On older REDCap versions, the escape() method can be used now by copying it into your module class 
from <newer-redcap-version-source>/ExternalModules/classes/ExternalModules.php.

  $_GET
    <no known location>

  $_GET['arm'] - ExternalModule.php:41:50
                $arm = empty($_GET['arm']) ? 1 : $_GET['arm'];

  $arm - ExternalModule.php:41:17
                $arm = empty($_GET['arm']) ? 1 : $_GET['arm'];

  call to LinearDataEntryWorkflow\ExternalModule\ExternalModule::loadRFIO - ExternalModule.php:43:44
                $this->loadRFIO($location, $arm, $record);

  LinearDataEntryWorkflow\ExternalModule\ExternalModule::loadRFIO#2 - ExternalModule.php:85:44
    protected function loadRFIO($location, $arm, $record = null, $event_id = null, $instrument = null) {

  $arm - ExternalModule.php:85:44
    protected function loadRFIO($location, $arm, $record = null, $event_id = null, $instrument = null) {

  concat - ExternalModule.php:189:29
            $this->redirect(APP_PATH_WEBROOT . 'DataEntry/record_home.php?pid=' . $Proj->project_id . '&id=' . $record . '&arm=' . $arm);

  call to LinearDataEntryWorkflow\ExternalModule\ExternalModule::redirect - ExternalModule.php:189:29
            $this->redirect(APP_PATH_WEBROOT . 'DataEntry/record_home.php?pid=' . $Proj->project_id . '&id=' . $record . '&arm=' . $arm);

  LinearDataEntryWorkflow\ExternalModule\ExternalModule::redirect#1 - ExternalModule.php:326:33
    protected function redirect($url) {

  $url - ExternalModule.php:326:33
    protected function redirect($url) {

  concat - ExternalModule.php:329:18
            echo '<script>window.location.href="' . $url . '";</script>';

  concat - ExternalModule.php:329:18
            echo '<script>window.location.href="' . $url . '";</script>';

  call to echo - ExternalModule.php:329:18
            echo '<script>window.location.href="' . $url . '";</script>';



ERROR: TaintedHtml - ExternalModule.php:329:18 - Detected tainted HTML (see https://psalm.dev/245)
This is generally resolved by finding the simplest highlighted variable in the trace below (ideally a short string)
and wrapping it in htmlspecialchars($taintedString, ENT_QUOTES). In REDCap version 13.1.2, a $module->escape() method
was added that avoids boilerplate in more complex cases by recursively escaping arrays and preserving primitive types.
It will become the recommendation once most institutions update to that REDCap version.
On older REDCap versions, the escape() method can be used now by copying it into your module class 
from <newer-redcap-version-source>/ExternalModules/classes/ExternalModules.php.

  $_GET
    <no known location>

  $_GET['arm'] - ExternalModule.php:41:50
                $arm = empty($_GET['arm']) ? 1 : $_GET['arm'];

  $arm - ExternalModule.php:41:17
                $arm = empty($_GET['arm']) ? 1 : $_GET['arm'];

  call to LinearDataEntryWorkflow\ExternalModule\ExternalModule::loadRFIO - ExternalModule.php:43:44
                $this->loadRFIO($location, $arm, $record);

  LinearDataEntryWorkflow\ExternalModule\ExternalModule::loadRFIO#2 - ExternalModule.php:85:44
    protected function loadRFIO($location, $arm, $record = null, $event_id = null, $instrument = null) {

  $arm - ExternalModule.php:85:44
    protected function loadRFIO($location, $arm, $record = null, $event_id = null, $instrument = null) {

  concat - ExternalModule.php:189:29
            $this->redirect(APP_PATH_WEBROOT . 'DataEntry/record_home.php?pid=' . $Proj->project_id . '&id=' . $record . '&arm=' . $arm);

  call to LinearDataEntryWorkflow\ExternalModule\ExternalModule::redirect - ExternalModule.php:189:29
            $this->redirect(APP_PATH_WEBROOT . 'DataEntry/record_home.php?pid=' . $Proj->project_id . '&id=' . $record . '&arm=' . $arm);

  LinearDataEntryWorkflow\ExternalModule\ExternalModule::redirect#1 - ExternalModule.php:326:33
    protected function redirect($url) {

  $url - ExternalModule.php:326:33
    protected function redirect($url) {

  concat - ExternalModule.php:329:18
            echo '<script>window.location.href="' . $url . '";</script>';

  concat - ExternalModule.php:329:18
            echo '<script>window.location.href="' . $url . '";</script>';

  call to echo - ExternalModule.php:329:18
            echo '<script>window.location.href="' . $url . '";</script>';



ERROR: TaintedHeader - ExternalModule.php:333:20 - Detected tainted header (see https://psalm.dev/256)

  $_GET
    <no known location>

  $_GET['arm'] - ExternalModule.php:41:50
                $arm = empty($_GET['arm']) ? 1 : $_GET['arm'];

  $arm - ExternalModule.php:41:17
                $arm = empty($_GET['arm']) ? 1 : $_GET['arm'];

  call to LinearDataEntryWorkflow\ExternalModule\ExternalModule::loadRFIO - ExternalModule.php:43:44
                $this->loadRFIO($location, $arm, $record);

  LinearDataEntryWorkflow\ExternalModule\ExternalModule::loadRFIO#2 - ExternalModule.php:85:44
    protected function loadRFIO($location, $arm, $record = null, $event_id = null, $instrument = null) {

  $arm - ExternalModule.php:85:44
    protected function loadRFIO($location, $arm, $record = null, $event_id = null, $instrument = null) {

  concat - ExternalModule.php:189:29
            $this->redirect(APP_PATH_WEBROOT . 'DataEntry/record_home.php?pid=' . $Proj->project_id . '&id=' . $record . '&arm=' . $arm);

  call to LinearDataEntryWorkflow\ExternalModule\ExternalModule::redirect - ExternalModule.php:189:29
            $this->redirect(APP_PATH_WEBROOT . 'DataEntry/record_home.php?pid=' . $Proj->project_id . '&id=' . $record . '&arm=' . $arm);

  LinearDataEntryWorkflow\ExternalModule\ExternalModule::redirect#1 - ExternalModule.php:326:33
    protected function redirect($url) {

  $url - ExternalModule.php:326:33
    protected function redirect($url) {

  concat - ExternalModule.php:333:20
            header('Location: ' . $url);

  call to header - ExternalModule.php:333:20
            header('Location: ' . $url);



------------------------------
3 errors found
------------------------------

Checks took 34.70 seconds and used 621.625MB of memory
Psalm was able to infer types for 59.8039% of the codebase
```

### PR DESCRIPTION
**Pull request by ChemiKyle**
Close #60

### CODE REVIEW

**Comment by pbchase** [comment]
The revised module does pass the test, but it now has no effect. If I checkout the develop branch, the desired effect returns.

File: ExternalModule.php [hunk 1]
```diff
@@ -34,11 +34,11 @@ function hook_every_page_top($project_id) {
                     break;
                 }
 
-                $record = $_GET['id'];
+                $record = $module->escape($_GET['id']);
```
Comment (ChemiKyle) [inline ExternalModule.php]: ~~`$module->escape(NULL)` throws an error!~~ `$module` isn't defined, whoops!

**Comment by ChemiKyle** [comment]
@pbchase this is ready for review
